### ISSUE TITLE
Implement verbose mode

### ISSUE THREAD

**Issue by quantumsheep** [QuantumSheep/warshield-cli#1]
**Implement -v/--verbose option.**

WarShield needs to have less informations by default than now and a verbose mode to display every information.

**Expected behavior without verbose:**
```
Scanning files... Done!
Encrypting files... Done!
Elapsed time: 16.27s
Total encrypted files: 1653
Failed: 3 (read-only files)
```

**Expected behavior with verbose:**
```
Added file /etc/nginx/conf.d
Added file /etc/nginx/fastcgi.conf
Added file /etc/nginx/sites-available/default
Added file /etc/nginx/sites-enabled/default
Done encrypting file /etc/nginx/conf.d
Done encrypting /etc/nginx/fastcgi.conf
Done encrypting /etc/nginx/sites-available/default
Done encrypting /etc/nginx/sites-enabled/default
Finished encrypting files!
Elapsed time: 0.76s
Total encrypted files: 4
Failed: 0 (read-only files)
```

**Comment by masihtamsoy** [comment]
Hi, I want to pick this up. Is it available? I have not worked with CLI. It’s my first attempt. Can you provide info to get me going?

**Comment by QuantumSheep** [comment]
I just finished verbose option but if you want you can take #2 😃

**Comment by quantumsheep** [comment]
@masihtamsoy I just finished verbose option but if you want you can take #2 😃
