### ISSUE TITLE
Interactive UI [suggestion]

### ISSUE THREAD

**Issue by anto-christo** [QuantumSheep/warshield-cli#6]
Hi, I am here from your dev.to comment.

I have experience in building a couple of CLIs. I personally prefer CLIs that have an interactive UI. Below is the demo of a CLI that I built for merging PDF files.

![demo](https://user-images.githubusercontent.com/22641196/56862855-eb186480-69cc-11e9-9581-eb4c441f274e.gif)

In case you are interested in having such an interactive UI for warshield, I'll be glad to help.
If such a UI is not required, let me know if there is anything else that I can do to contribute.
Thank you.

**Comment by quantumsheep** [comment]
I think that it would be pretty cool to have such UI but we need to keep the current one-command encryption and decryption. Maybe a `--ui` option or `--cli` in reverse? If you're ready to help and implement this option then I'm ok to have this option in WarShield :)

**Comment by anto-christo** [comment]
Hi,
Currently typing just `warshield` in the command lines displays the help. Maybe we can override this and show the interface when just `warshield` is typed by the user. Or, as per your suggestion, the `--ui` option sounds alright as well.

Let me know which one you prefer and would like to finalise. Thank you.

**Comment by quantumsheep** [comment]
Oh that's a great idea! It's better than an option! I'm good with replacing the current default action by the UI.

**Comment by anto-christo** [comment]
Added this feature in #8
