### ISSUE TITLE
TypeError: encryptFile(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by anto-christo** [QuantumSheep/warshield-cli#7]
Hi,
I was trying to run the CLI. However, I am not able to encrypt any file and always get the following error no matter which file. (I tried to run on both Windows 10 and Ubuntu 18)

![warshield-error](https://user-images.githubusercontent.com/22641196/56959540-5861fc00-6b6b-11e9-9ef8-5374d2232025.png)

As per my knowledge, these files are not read-only and the user does have access to them.
What may be the possible reasons for this error?
Any help in this regard is appreciated. Thank you.

**Comment by quantumsheep** [comment]
Hi,
Use `-v` or `--verbose` option to see exactly what goes wrong with your files.

**Comment by anto-christo** [comment]
Hi,
Adding the -v flag said it failed to add the file, i.e the file was not found. Running the command again with the file extension removed this error. Earlier I was just typing the file name without the extension.

However, the following new error has popped out.
```
E:\Code\warshield\warshield.js:280
        .finally(() => em.emit('end'));
                ^

TypeError: encryptFile(...).then(...).catch(...).finally is not a function
    at fs.stat (E:\Code\warshield\warshield.js:280:17)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

Below is the part of code throwing the error.
```
encryptFile(file, key, tmp)
        .then(() => em.emit('done', file))
        .catch(() => em.emit('failed', file))
        .finally(() => em.emit('end'));
```
I searched online and found out that support for `.finally` may not be there in certain versions of Node.js. I think this maybe the issue here as well. Your thoughts on this? and May I know what version of Node.js are you using?

Just for the sake of running it, I modified the above code to as below and it worked perfectly fine.
```
encryptFile(file, key, tmp)
        .then(() => {
          em.emit('done', file)
          em.emit('end')
        })
        .catch(() => {
          em.emit('failed', file)
          em.emit('end')
        })
```

**Comment by quantumsheep** [comment]
It seems that your NodeJS version is outdated, my bad for not telling the minimum version required. I'm currently using NodeJS 10.15 since it's the LTS (and `.finally()` seems to be present from v10.x).

**Comment by anto-christo** [comment]
Upgrading Node.js to v10.x resolved the issue. Thank you.

**Comment by quantumsheep** [comment]
Precised in commit https://github.com/quantumsheep/warshield/commit/bc70546c19c8b751f8db9243ec40d3ccb8cd9de4
