### ISSUE TITLE
Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by n-rocher** [QuantumSheep/warshield-cli#9]
Hello,
I don't understand why i'm getting this error on Windows 10...

Everything is fine when i encrypt file but when I want to decrypt it, I get this error...

Thank's.

**Comment by quantumsheep** [comment]
Hi, can you provide the WarShield's version you're using? (`warshield -V`)
And also give the full logs when using verbose mode? (`warshield -v` or select "verbose" on the UI)

**Comment by n-rocher** [comment]
No it's okay.
The content of my file **was modified by another program** during the laps of time.
And I think the code (below) didn't expect that. (file : src/warshield.js)

In the decryptFile method :
```
const { buffer: bufs } = await read(fd, Buffer.alloc(100), 0, 100, 0);
const salt = bufs.slice(0, 64);
const iv = bufs.slice(64, 80);
const tag = bufs.slice(80, 96);
const rounds = bufs.slice(96, 100);
```

Thank you for answering so quickly.

**Comment by quantumsheep** [comment]
Yeah, their is some information stored in the encrypted file that are needed to decrypt it. Happy to see that your issue is fix, have a nice day :)
